addons:
  apt:
    packages:
    - libgmp-dev
language: ruby
rvm:
  - 2.4.0
  - 2.3.0
  - 2.2.4
  - 2.2.3
  - 2.2.2
  - 2.1.8
before_install: gem install bundler
after_success: bundle exec codeclimate-test-reporter
